# File: .github/workflows/trade.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas yfinance ta lxml


name: Run Trading Algo and Deploy

on:
  schedule:
    - cron: '0 14 * * 1-5' # every weekday at 2PM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas yfinance ta

    - name: Run Trading Script
      run: python Dynamic_Trading_Algo.py

    - name: Commit HTML dashboard
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add dashboard.html
        git diff --cached --quiet || git commit -m "Update dashboard"
        git push

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
